-- CREATE TABLE MEMBER (
--     ID VARCHAR(255) NOT NULL,
--     NAME VARCHAR(255),
--     AGE INTEGER,
--     PRIMARY KEY (ID)
-- )
CREATE TABLE MEMBER (
    MEMBER_ID VARCHAR(255) NOT NULL,
    TEAM_ID VARCHAR(255),
    USERNAME VARCHAR255,
    PRIMARY KEY (MEMBER_ID)
)
CREATE TABLE TEAM(
    TEAM_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR255,
    PRIMARY KEY (TEAM_ID)
)
ALTER TABLE MEMBERADD CONSTRAINT FK_MEMBER_TEAM
        FOREIGN KEY (TEAM_ID)
        REFERENCES TEAM